SESSIONS_SCHEMA = {"sessionid": "integer PRIMARY KEY AUTOINCREMENT", 
                    "date": "text", 
                    "time_start": "text", 
                    "time_end": "text", 
                    "type": "text",
                    "session_title": "text", 
                    "location": "text", 
                    "description": "text", 
                    "speakers": "text"}
SUBSESSIONS_SCHEMA = {"subsessionid": "integer PRIMARY KEY AUTOINCREMENT", 
                        "date": "text", 
                        "time_start": "text", 
                        "time_end": "text", 
                        "type": "text",
                        "session_title": "text", 
                        "location": "text", 
                        "description": "text", 
                        "speakers": "text", 
                        "parent_session": "integer",
                        "FOREIGN KEY (parent_session)": "REFERENCES sessions(sessionid)"}
SPEAKER_TO_SESSION_SCHEMA = {"id": "integer PRIMARY KEY AUTOINCREMENT", 
                            "speaker": "text", 
                            "sessionid": "integer",
                            "FOREIGN KEY (sessionid)": "REFERENCES sessions(sessionid)"}
SPEAKER_TO_SUBSESSION_SCHEMA = {"id": "integer PRIMARY KEY AUTOINCREMENT", 
                            "speaker": "text", 
                            "subsessionid": "integer",
                            "FOREIGN KEY (subsessionid)": "REFERENCES subsessions(subsessionid)"}